### ISSUE TITLE
I'm running into this error, I don't know what it could be

### ISSUE THREAD

**Issue by manuelduarte077** [mrrhak/icons_launcher#16]
### :information_source: Info

Version: `icons_launcher: ^2.0.0

### :speech_balloon: Description

Unhandled exception:
```bash
type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      hasPlatformConfig (package:icons_launcher/utils/utils.dart:4:41)
#1      _checkConfig (package:icons_launcher/cli_commands.dart:85:8)
#2      createLauncherIcons (package:icons_launcher/cli_commands.dart:28:3)
#3      main (file:///Users/manuel/.pub-cache/hosted/pub.dartlang.org/icons_launcher-2.0.0/bin/create.dart:15:3)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

### :scroll: Pubspec.yaml
```
icons_launcher:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: 'assets/icon/logo.png'
  image_path_android: 'assets/icon/logo.png'
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_background_image: 'assets/icon/app-icon-background.png'
  adaptive_foreground_image: 'assets/icon/app-icon-foreground.png'
```

**Comment by mrrhak** [comment]
Hi, @manuelduarte077 
We have changed the config schema in version 2.0.0 you can look at [change log](https://pub.dev/packages/icons_launcher/changelog) or [example](https://github.com/mrrhak/icons_launcher/tree/master/example/simple_app)

**Comment by mrrhak** [comment]
You can replace your config with this

```yaml
icons_launcher:
  platforms:
    android:
      enable: true
      image_path: 'assets/icon/logo.png'
      adaptive_background_image: 'assets/icon/app-icon-background.png'
      adaptive_foreground_image: 'assets/icon/app-icon-foreground.png'
    ios:
      enable: true
      image_path: 'assets/icon/logo.png'
```
