### ISSUE TITLE
`ic_launcher_round.png` not removed when property `adaptive_round_image` is removed

### ISSUE THREAD

**Issue by OutdatedGuy** [mrrhak/icons_launcher#18]
### :information_source: Info

Version: `e.g. v2.0.1`
Platform: `Android`

### :speech_balloon: Description

If property `adaptive_round_image` is removed then the generated `ic_launcher_round.png` images are not removed from `res` folder.

### :scroll: Pubspec.yaml

```yaml
# For App Launcher icon
# flutter pub run icons_launcher:create
icons_launcher:
  image_path: "assets/icons/launcher_icon_border.png"

  platforms:
    android:
      enable: true
      adaptive_background_color: "#673AB7"
      adaptive_foreground_image: "assets/icons/adaptive_logo.png"

    ios:
      enable: false

    web:
      enable: true
      favicon_path: "assets/icons/favicon.png"

    macos:
      enable: false

    windows:
      enable: false

    linux:
      enable: false
```
