### ISSUE TITLE
[BUG] snap/gui/app_icon.desktop replaced on icons_launcher:create.

### ISSUE THREAD

**Issue by fredrikbaberg** [mrrhak/icons_launcher#23]
### :information_source: Info

v2.0.5

### :speech_balloon: Description

When running `flutter pub run icons_launcher:create`, the file `snap/gui/app_icon.desktop` is overwritten by an example file. For example, I have changed Name and Comment in the file and this is replaced by the default values:
```
Name=Flutter Linux App
Comment=Flutter Linux launcher icon
```

### :scroll: Pubspec.yaml

`icons_launcher.yaml` as follows:

```
icons_launcher:
  image_path: "assets/icons/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: false
    linux:
      enable: true
    macos:
      enable: false
    web:
      enable: true
    windows:
      enable: true
```
