### ISSUE TITLE
[BUG] Android adaptive icon not displaying properly

### ISSUE THREAD

**Issue by agramian** [mrrhak/icons_launcher#3]
### :information_source: Info

Version: `^1.1.3`

### :speech_balloon: Description

The android adaptive icon is not displaying properly.  See the screenshot below.  The "default_e..." entry is from the example project in this repo and the "mobile" entry is from my personal project which has a solid white png for the background image and a black icon centered over transparency for the foreground image.
   
![Screenshot_1651746531](https://user-images.githubusercontent.com/7113257/166906689-eca597e7-ac67-4c8f-a4b6-f8ec173b87b6.png)

Flutter version info:
```
 Flutter version 2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
```

Android info:
```
Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Platform android-31, build-tools 31.0.0
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

Android Studio (version 2021.1)
    • Flutter plugin version 66.0.1
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

Connected device
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
```

The screenshot is from a Pixel 4 API 31 emulator but is also reproducible on a physical device.

### :scroll: Pubspec.yaml

Copied from the example project in this repo:
```
name: example
description: A new Flutter project to quickly test flutter_launcher_icons.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher:
    path: ../

flutter:

  uses-material-design: true
```
