### ISSUE TITLE
[BUG] Debug build fails when using adaptive icon foreground

### ISSUE THREAD

**Issue by whygee-dev** [mrrhak/icons_launcher#4]
### :information_source: Info

Version: `>=1.1.4`

### :speech_balloon: Description

Debug build fails:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     <stripped>\app\android\app\src\main\res\mipmap-anydpi-v26\ic_launcher.xml:4: AAPT: error: resource drawable/ic_launcher_foreground (aka com.example.app:drawable/ic_launcher_foreground) not found.

### :scroll: Pubspec.yaml

```yaml
name: <stripped>
description: <stripped>

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.1
  vrouter: ^1.2.0+21
  google_fonts: ^2.3.2

dev_dependencies:
  flutter_app_name: ^0.1.1
  icons_launcher: "^1.1.4"
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo-bg.png"
  adaptive_icon_background: "#242424"
  adaptive_icon_foreground: "assets/logo.png"

flutter_native_splash:
  background_image: "assets/splashscreen_background.png"
  image: "assets/logo.png"

flutter_app_name:
  name: <stripped>

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
```

**Comment by mrrhak** [comment]
Make sure your android \res\mipmap-anydpi-v26\ic_launcher.xml is load image from mipmap like this

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@mipmap/ic_launcher_background"/>
  <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
```

and make sure images are generated to android \res\mipmap completely. Thanks

**Comment by whygee-dev** [comment]
Here's my \res\mipmap-anydpi-v26\ic_launcher.xml

```yaml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/ic_launcher_background"/>
  <foreground android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
```

Images did get generated inside \res\mipmap-xxxx
![Screenshot_20](https://user-images.githubusercontent.com/76694551/167329868-95cfdaf4-1432-4ea4-8c09-4861e61906ba.png)

**Comment by mrrhak** [comment]
Ohh I got it. The plugin generate ic_launcher.xml incorrect I will fix it on next version. Now you can fix it by replacing `@drawable` to `@mipmap` in your ic_launcher.xml.

**Comment by whygee-dev** [comment]
That did solve it indeed

**Comment by mrrhak** [comment]
[New release](https://pub.dev/packages/icons_launcher) is fixed this issue. Thanks

**Comment by sbritorodr** [comment]
I'm having the same issue after the update, this is my pubspec.yaml file

```yaml
flutter_icons:
  image_path: "assets/icon/applogo.png" #or .png
  adaptive_icon_background: "#000000"
  android: true
  ios: true
```
