### ISSUE TITLE
[BUG] Index out of range error when trying to generate icons

### ISSUE THREAD

**Issue by adar2378** [mrrhak/icons_launcher#40]
It happens when I run `flutter pub run flutter_launcher_icons`
### :information_source: Info
Version: `v2.1.3`

### :speech_balloon: Description
```bash
🌱  Creating Android icons...
Unhandled exception:
RangeError (index): Index out of range: index should be less than 9216: 9252
#0      Uint8List.[]= (dart:typed_data-patch/typed_data_patch.dart:2280:7)
#1      ImageDataUint8.setPixelRgba (package:image/src/image/image_data_uint8.dart:111:9)
#2      Image.setPixel (package:image/src/image/image.dart:761:11)
#3      copyResize (package:image/src/transform/copy_resize.dart:132:15)
#4      Icon.copyResized (package:icons_launcher/utils/icon.dart:57:21)
#5      Icon.saveResizedPng (package:icons_launcher/utils/icon.dart:75:28)
#6      _saveImageAndroid (package:icons_launcher/src/android.dart:56:9)
#7      _createAndroidIcons (package:icons_launcher/src/android.dart:33:5)
#8      _createIconsByConfig (package:icons_launcher/cli_commands.dart:340:7)
#9      createLauncherIcons (package:icons_launcher/cli_commands.dart:29:3)
#10     main (file:///Users/saifulislam/.pub-cache/hosted/pub.dev/icons_launcher-2.1.3/bin/create.dart:15:3)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

### :scroll: Pubspec.yaml

icons_launcher.yaml
```
icons_launcher:
  image_path: "assets/app_logo/logo.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/app_logo/logo.png"
      adaptive_round_image: "assets/app_logo/logo_round.png"
    ios:
      enable: true
    web:
      enable: true

```
