### ISSUE TITLE
[BUG] Wrong icon size on A13

### ISSUE THREAD

**Issue by vodemn** [mrrhak/icons_launcher#43]
### :information_source: Info

Version: `v2.1.5`

### :speech_balloon: Description

I've checked the [example icons](https://github.com/mrrhak/icons_launcher/tree/master/example/flavor_app/assets) and they are 1024x1024. I've used icon of the same size for my app, but the resulting icon is too big on my Pixel 6 and Samsung Galaxy S20+ both running Android 13.

<details>
  <summary>Samsung Galaxy S20+ 5G (Android 13)</summary>
<img width="455" alt="Screenshot 2023-11-21 at 09 49 58" src="https://github.com/mrrhak/icons_launcher/assets/44135514/cd20613b-0e22-4369-bbf3-c1870eedebf7">
</details>

### :scroll: icons_launcher-prod.yaml

```yaml
icons_launcher:
  image_path: "assets/launcher_icon_circle.png"
  platforms:
    android:
      enable: true
      image_path: "assets/launcher_icon_circle.png"
      adaptive_background_color: '#212121'
      adaptive_foreground_image: "assets/launcher_icon_circle.png"
      adaptive_round_image: "assets/launcher_icon_circle.png"
```

```console
dart run icons_launcher:create --flavor prod
```

<details>
  <summary>launcher_icon_square.png</summary>
![Icon square](https://github.com/mrrhak/icons_launcher/assets/44135514/9cd7d65c-660c-400a-beba-7acfcb16039a)
</details>

<details>
  <summary>launcher_icon_circle.png</summary>
![output-onlinepngtools (3)](https://github.com/mrrhak/icons_launcher/assets/44135514/8b7bb148-41be-4d63-8738-8811aeda1bcf)
</details>
