### ISSUE TITLE
[BUG] image resizing bad quality

### ISSUE THREAD

**Issue by lukepighetti** [mrrhak/icons_launcher#58]
source image:

![icon-fg](https://github.com/user-attachments/assets/3cb15d35-217a-4dae-886a-30026504a55c)

output image: 

![ic_launcher_foreground](https://github.com/user-attachments/assets/033015c4-31f0-4987-a7fa-73b99ec2399f)

```yaml
icons_launcher:
  image_path: assets/icon.png
  platforms:
    android:
      enable: true
      adaptive_foreground_image: "assets/icon-fg.png"
```

```
  icons_launcher:
    dependency: "direct dev"
    description:
      name: icons_launcher
      sha256: "9b514ffed6ed69b232fd2bf34c44878c8526be71fc74129a658f35c04c9d4a9d"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.7"
```
