### ISSUE TITLE
[BUG] mipmap/ic_launcher_round not found

### ISSUE THREAD

**Issue by schuberty** [mrrhak/icons_launcher#6]
### :information_source: Info

Version: `v1.1.17`

### :speech_balloon: Description

I have my pubspec.yaml like the following for this package:

### :scroll: Pubspec.yaml

```dart
# Depends on `icons_launcher`
flutter_icons:
  ios: true
  android: true
  # iOS requires entire image
  image_path: "assets/launcher/icon_square.png"
  # Otherwise, Android don't
  adaptive_icon_round: "assets/launcher/icon_rounded.png"
  adaptive_icon_background: "#FFA500"
```

When I run all goes well

> ➜ flutter pub run icons_launcher:main

But when I run into the devices I only keep getting the following error:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:E:\Development\Com\App\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:17: AAPT: error: resource mipmap/ic_launcher_round (aka com.app:mipmap/ic_launcher_round) not found.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
```

**Comment by mrrhak** [comment]
- Android adaptive icon will generate if you provide `adaptive_icon_background ` and `adaptive_icon_foreground`.
- `adaptive_icon_round` is optional,  if you provide you must provide two config above also, the plugin will modify your ` AndroidMainifest.xml` to add `android:roundIcon="@mipmap/ic_launcher_round` and create a new file `ic_launcher_round.xml` to `mipmap-anydpi-v26`

Exampe:
- Correct ✅
```yaml
flutter_icons:
  image_path: "assets/logo.png"
  android: true
```

- Correct ✅
```yaml
flutter_icons:
  image_path: "assets/logo.png"
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
```

- Correct ✅
```yaml
flutter_icons:
  image_path: "assets/logo.png"
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_round: "assets/logo_round.png"
```

---

- Incorrect ❌
```yaml
flutter_icons:
  image_path: "assets/logo.png"
  android: true
  adaptive_icon_background: "#ffffff"
```

- Incorrect ❌
```yaml
flutter_icons:
  image_path: "assets/logo.png"
  android: true
  adaptive_icon_round: "assets/logo_round.png"
```

However in your case I see your  ` AndroidMainifest.xml` is already include `android:roundIcon="@mipmap/ic_launcher_round` but you don't have `ic_launcher_round` resources exsited.
