### ISSUE TITLE
[BUG] The generated icon has filling lag when echoed on Android 13

### ISSUE THREAD

**Issue by maxfrees** [mrrhak/icons_launcher#65]
The generated icon has filling lag when echoed on Android 13

It gets smaller and then it gets bigger again, so my picture is 1024 x 1024

**Comment by mrrhak** [comment]
Could you provide an example?

**Comment by maxfrees** [comment]
![launcher_icon](https://github.com/user-attachments/assets/cb118b53-5e6c-4c76-b543-397d85dfd28f)

```
icons_launcher:
  image_path: "assets/ic_logo_radius.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
```
