### ISSUE TITLE
[BUG] White background for the launcher icon

### ISSUE THREAD

**Issue by sudheersuri** [mrrhak/icons_launcher#67]
Version: `3.0.0`

It's generating white background 

![image](https://github.com/user-attachments/assets/a8a1a3e3-fa39-4cba-95a2-e0103ece41ed)

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: 'assets/images/icon.png'
  adaptive_background_color: '#1B1B1B'
  platforms:
    android:
      enable: true
```

**Comment by mrrhak** [comment]
Hi @sudheersuri, look like your configuration `adaptive_background_color ` setup is incorrect. Please try this instead

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: 'assets/images/icon.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#1B1B1B'
```
