### ISSUE TITLE
[BUG] Linux App Icon Not Portrayed

### ISSUE THREAD

**Issue by ghost** [mrrhak/icons_launcher#69]
### :information_source: Info

icons_launcher version: `^v3.0.0`
Operating System: `Ubuntu 24.04.1 LTS`
Flutter version info:
```
Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (6 days ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3
```

### :speech_balloon: Description

No problem is reported during `dart run icons_launcher:create`. Furthermore, it appears the snap icon is correctly built within the `snap` directory. However, the Linux application does not portray any icon.

### :scroll: Pubspec.yaml

pubspec.yaml
```yaml
name: halkyon_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true
```

icons_launcher.yaml
```yaml
icons_launcher:
  image_path: "assets/branding/app-icon-rounded.png"
  platforms:
    android:
      enable: true
      image_path: "assets/branding/app-icon-angular-cropped.png"
      # notification_image: <PATH>
      # adaptive_background_color: '#ffffff'
      # adaptive_background_image: <PATH>
      # adaptive_foreground_image: <PATH>
      # adaptive_round_image: <PATH>
      # adaptive_monochrome_image: <PATH>
    ios:
      enable: true
      image_path: "assets/branding/app-icon-rounded.png"
      # For iOS 18+ (support dark and tinted)
      # dark_path: <PATH>
      # tinted_path: <PATH>
    web:
      enable: true
      image_path: "assets/branding/app-icon-rounded.png"
      # favicon_path: <PATH>
    macos:
      enable: true
      image_path: "assets/branding/app-icon-rounded.png"
    windows:
      enable: true
      image_path: "assets/branding/app-icon-rounded.png"
    linux:
      enable: true
      image_path: "assets/branding/app-icon-rounded.png"
```

The complete source code can be found [here](https://codeberg.org/halkyonproject/halkyon-app) on Codeberg.
