### ISSUE TITLE
[BUG] cannot create launcher icons on macos

### ISSUE THREAD

**Issue by AniketMalik** [mrrhak/icons_launcher#7]
### :information_source: Info

Version: `1.1.8`

### :speech_balloon: Description

The launcher icons could not be created due to invalid config.

Output from shell:
```shell

═════════════════════════════════════════════
      ✨  ICONS LAUNCHER STARTING  ✨
                   v1.1.8
═════════════════════════════════════════════


✕ Could not generate launcher icons

✗ ERROR: InvalidConfigException 
No platform specified within config to generate icons for.
pub finished with exit code 2


```

### :scroll: Pubspec.yaml

```yaml
# ...
flutter_icons:
  macos: true
  image_path: 'assets/images/launcher-icon.png'
# ...
```
